---
ISTIO_PRIVATE_GATEWAY_NAME: private-gateway
ISTIO_PUBLIC_GATEWAY_NAME: public-gateway
PUBLIC_FB_SERVICE_NAME: public-fallback-service
PRIVATE_FB_SERVICE_NAME: private-fallback-service
PUBLIC_SERVICE: "public-frontend-gateway"
PRIVATE_SERVICE: "private-frontend-gateway"
PRIVATE_GW_ROUTE_NAME: fallback-to-private-gateway
PUBLIC_GW_ROUTE_NAME: fallback-to-public-gateway

ISTIO_EGRESS_GATEWAY_NAME: egress-gateway
EGRESS_FB_SERVICE_NAME: egress-fallback-service
EGRESS_GATEWAY_SERVICE_NAME: "egress-gateway"
EGRESS_GATEWAY_SERVICE: "egress-gateway-gateway"

WAYPOINT_NAME: waypoint

# contract parameters - do not change name
APPLICATION_NAME: "Cloud-Core"
SKIP_EGRESS_GATEWAY_CREATION: false
SERVICE_NAME: "qubership-core-mesh"
SERVICE_MESH_TYPE : "Core"   # or "Istio"

CLOUD_TOPOLOGY_KEY: kubernetes.io/hostname