ISTIO_PRIVATE_GATEWAY_NAME: private-gateway
ISTIO_PUBLIC_GATEWAY_NAME: public-gateway
PUBLIC_FB_SERVICE_NAME: public-fallback-service
PRIVATE_FB_SERVICE_NAME: private-fallback-service
PUBLIC_SERVICE: "public-frontend-gateway"
PUBLIC_SERVICE_NAME: "public-gateway-service"
PRIVATE_SERVICE: "private-frontend-gateway"
PRIVATE_SERVICE_NAME: "private-gateway-service"
PRIVATE_GW_ROUTE_NAME: fallback-to-private-gateway
PUBLIC_GW_ROUTE_NAME: fallback-to-public-gateway

ISTIO_EGRESS_GATEWAY_NAME: egress-gateway
EGRESS_FB_SERVICE_NAME: egress-fallback-service 
SKIP_EGRESS_GATEWAY_CREATION: false
EGRESS_GATEWAY_SERVICE_NAME: "egress-gateway"
EGRESS_GATEWAY_SERVICE: "egress-gateway-gateway"

APPLICATION_NAME: "Cloud-Core"
SERVICE_NAME: "qubership-core-mesh-config"