{{- if eq .Values.SERVICE_MESH_TYPE "Istio" }}
{{- if not .Values.SKIP_EGRESS_GATEWAY_CREATION }}
---
kind: Service
apiVersion: v1
metadata:
  name: '{{ .Values.EGRESS_FB_SERVICE_NAME }}'
  annotations:
    helm.sh/hook: "pre-install, pre-upgrade"
    helm.sh/hook-weight: "-80"
    helm.sh/hook-delete-policy: "before-hook-creation"    
spec:
  ports:
    - name: web
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    name: '{{ .Values.EGRESS_GATEWAY_SERVICE }}'
  clusterIP: None
  clusterIPs:
    - None
  type: ClusterIP
  sessionAffinity: None
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  internalTrafficPolicy: Cluster 
---
kind: Service
apiVersion: v1
metadata:
    name: '{{ .Values.EGRESS_GATEWAY_SERVICE_NAME }}'
    annotations:
      helm.sh/hook: "post-install, post-upgrade"
      helm.sh/hook-weight: "110"
      helm.sh/hook-delete-policy: "before-hook-creation"
spec:
  ports:
    - name: web
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    gateway.networking.k8s.io/gateway-name: 'ns-{{ .Values.ISTIO_EGRESS_GATEWAY_NAME }}'
  clusterIP: None
  clusterIPs:
    - None
  type: ClusterIP
  sessionAffinity: None
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  internalTrafficPolicy: Cluster 
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: ns-{{ .Values.ISTIO_EGRESS_GATEWAY_NAME }}
  annotations:
    helm.sh/hook: "pre-install, pre-upgrade"
    helm.sh/hook-weight: "-100"
    helm.sh/hook-delete-policy: "before-hook-creation"
spec:
  gatewayClassName: istio
  listeners:
  - name: http
    port: 8080
    protocol: HTTP
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: '{{ .Values.ISTIO_EGRESS_GATEWAY_NAME }}-route'
  annotations:
    helm.sh/hook: "pre-install, pre-upgrade"
    helm.sh/hook-weight: "-60"
    helm.sh/hook-delete-policy: "before-hook-creation"
    helm.sh/readiness-success: |
      {.status.parents[*].conditions[?(@.type=="Accepted")].status} != "False" &&
      {.status.parents[*].conditions[?(@.type=="ResolvedRefs")].status} != "False"    
    helm.sh/readiness-failure: |
      {.status.parents[*].conditions[?(@.type=="Accepted")].status} == "False" ||
      {.status.parents[*].conditions[?(@.type=="ResolvedRefs")].status} == "False"
  labels:
    app.kubernetes.io/name: '{{ .Values.SERVICE_NAME }}'
spec:
  parentRefs:
  - name: ns-{{ .Values.ISTIO_EGRESS_GATEWAY_NAME }}
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: '{{ .Values.EGRESS_FB_SERVICE_NAME }}'
      port: 8080
{{- end }}
{{- end }}