{{- if eq .Values.deploy_feature_flags.core.serviceMeshType "ISTIO" }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: '{{ .Values.ISTIO_PUBLIC_GATEWAY_NAME }}'
  annotations:
    helm.sh/hook: "pre-install, pre-upgrade"
    helm.sh/hook-weight: "-100"
    helm.sh/hook-delete-policy: "before-hook-creation"
    networking.istio.io/service-type: ClusterIP
  labels:
    app.kubernetes.io/name: '{{ .Values.ISTIO_PUBLIC_GATEWAY_NAME }}'
    app.kubernetes.io/instance: '{{ cat .Values.ISTIO_PUBLIC_GATEWAY_NAME "-" .Values.NAMESPACE | nospace | trunc 63 | trimSuffix "-" }}'
    app.kubernetes.io/component: '{{ .Values.SERVICE_NAME }}'
    app.kubernetes.io/version: '{{ .Chart.version }}'
    app.kubernetes.io/part-of: '{{ .Values.APPLICATION_NAME }}'
    app.kubernetes.io/managed-by: 'Helm'
    app.kubernetes.io/processed-by-operator: 'istiod'
spec:
  gatewayClassName: istio
  infrastructure:
    labels:
      app.kubernetes.io/name: '{{ .Values.ISTIO_PUBLIC_GATEWAY_NAME }}'
    podTemplate:
      metadata:
        labels:
          app.kubernetes.io/name: '{{ .Values.ISTIO_PUBLIC_GATEWAY_NAME }}'
      spec:
        containers:
        - name: istio-proxy
          resources:
            requests:
              cpu: {{ index .Values.gatewayProfiles .Values.GATEWAY_PROFILE "cpuRequest" | quote }}
              memory: {{ index .Values.gatewayProfiles .Values.GATEWAY_PROFILE "memRequest" | quote }}
            limits:
              cpu: {{ index .Values.gatewayProfiles .Values.GATEWAY_PROFILE "cpuLimit" | quote }}
              memory: {{ index .Values.gatewayProfiles .Values.GATEWAY_PROFILE "memLimit" | quote }}
        topologySpreadConstraints:
{{- if .Values.CLOUD_TOPOLOGIES }}
{{- range $v := .Values.CLOUD_TOPOLOGIES }}
          - topologyKey: {{ $v.topologyKey }}
            maxSkew: {{ $v.maxSkew | default 1 }}
            whenUnsatisfiable: {{ $v.whenUnsatisfiable | default "ScheduleAnyway" }}
            labelSelector:
              matchLabels:
                name: '{{ .Values.ISTIO_PUBLIC_GATEWAY_NAME }}'
{{- end }}
{{- else }}
          - maxSkew: 1
            topologyKey: '{{ .Values.CLOUD_TOPOLOGY_KEY }}'
            whenUnsatisfiable: ScheduleAnyway
            labelSelector:
              matchLabels:
                app.kubernetes.io/name: '{{ .Values.ISTIO_PUBLIC_GATEWAY_NAME }}'
{{- end }}
  listeners:
  - name: http
    port: 8080
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: All
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: '{{ .Values.ISTIO_PRIVATE_GATEWAY_NAME }}'
  annotations:
    helm.sh/hook: "pre-install, pre-upgrade"
    helm.sh/hook-weight: "-100"
    helm.sh/hook-delete-policy: "before-hook-creation"
    networking.istio.io/service-type: ClusterIP
  labels:
    app.kubernetes.io/name: '{{ .Values.ISTIO_PRIVATE_GATEWAY_NAME }}'
    app.kubernetes.io/instance: '{{ cat .Values.ISTIO_PRIVATE_GATEWAY_NAME "-" .Values.NAMESPACE | nospace | trunc 63 | trimSuffix "-" }}'
    app.kubernetes.io/component: '{{ .Values.SERVICE_NAME }}'
    app.kubernetes.io/version: '{{ .Chart.version }}'
    app.kubernetes.io/part-of: '{{ .Values.APPLICATION_NAME }}'
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/processed-by-operator: 'istiod'
spec:
  gatewayClassName: istio
  infrastructure:
    labels:
      app.kubernetes.io/name: '{{ .Values.ISTIO_PRIVATE_GATEWAY_NAME }}'
    podTemplate:
      metadata:
        labels:
          app.kubernetes.io/name: '{{ .Values.ISTIO_PRIVATE_GATEWAY_NAME }}'
      spec:
        containers:
        - name: istio-proxy
          resources:
            requests:
              cpu: {{ index .Values.gatewayProfiles .Values.GATEWAY_PROFILE "cpuRequest" | quote }}
              memory: {{ index .Values.gatewayProfiles .Values.GATEWAY_PROFILE "memRequest" | quote }}
            limits:
              cpu: {{ index .Values.gatewayProfiles .Values.GATEWAY_PROFILE "cpuLimit" | quote }}
              memory: {{ index .Values.gatewayProfiles .Values.GATEWAY_PROFILE "memLimit" | quote }}

        topologySpreadConstraints:
{{- if .Values.CLOUD_TOPOLOGIES }}
{{- range $v := .Values.CLOUD_TOPOLOGIES }}
          - topologyKey: {{ $v.topologyKey }}
            maxSkew: {{ $v.maxSkew | default 1 }}
            whenUnsatisfiable: {{ $v.whenUnsatisfiable | default "ScheduleAnyway" }}
            labelSelector:
              matchLabels:
                name: '{{ .Values.ISTIO_PRIVATE_GATEWAY_NAME }}'
{{- end }}
{{- else }}
          - maxSkew: 1
            topologyKey: "{{ .Values.CLOUD_TOPOLOGY_KEY }}"
            whenUnsatisfiable: ScheduleAnyway
            labelSelector:
              matchLabels:
                app.kubernetes.io/name: '{{ .Values.ISTIO_PRIVATE_GATEWAY_NAME }}'
{{- end }}
  listeners:
  - name: http
    port: 8080
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: All
{{- end }}