{{- if eq .Values.deploy_feature_flags.core.serviceMeshType "ISTIO" }}
{{- if not .Values.SKIP_EGRESS_GATEWAY_CREATION }}
---
kind: Service
apiVersion: v1
metadata:
  name: '{{ .Values.EGRESS_FB_SERVICE_NAME }}'
  annotations:
    helm.sh/hook: "pre-install, pre-upgrade"
    helm.sh/hook-weight: "-80"
    helm.sh/hook-delete-policy: "before-hook-creation"    
  labels:
    {{- include "myapp.labels" (dict "root" $ "name" .Values.EGRESS_FB_SERVICE_NAME "processedByOperator" false) | nindent 4 }}
spec:
  ports:
    - name: web
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    name: '{{ .Values.EGRESS_GATEWAY_SERVICE }}'
  clusterIP: None
  clusterIPs:
    - None
  type: ClusterIP
  sessionAffinity: None
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  internalTrafficPolicy: Cluster 
---
kind: Service
apiVersion: v1
metadata:
  name: '{{ .Values.EGRESS_GATEWAY_SERVICE_NAME }}'
  annotations:
    helm.sh/hook: "post-install, post-upgrade"
    helm.sh/hook-weight: "110"
    helm.sh/hook-delete-policy: "before-hook-creation"
  labels:
    {{- include "myapp.labels" (dict "root" $ "name" .Values.EGRESS_GATEWAY_SERVICE_NAME "processedByOperator" false) | nindent 4 }}
spec:
  ports:
    - name: web
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    gateway.networking.k8s.io/gateway-name: {{ printf "ns-%s" .Values.ISTIO_EGRESS_GATEWAY_NAME | quote }}
  clusterIP: None
  clusterIPs:
    - None
  type: ClusterIP
  sessionAffinity: None
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  internalTrafficPolicy: Cluster 
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ printf "ns-%s" .Values.ISTIO_EGRESS_GATEWAY_NAME }}
  annotations:
    helm.sh/hook: "pre-install, pre-upgrade"
    helm.sh/hook-weight: "-100"
    helm.sh/hook-delete-policy: "before-hook-creation"
  labels:
    {{- $gatewayName := printf "ns-%s" .Values.EGRESS_GATEWAY_SERVICE_NAME | trunc 63 -}}
    {{- include "myapp.labels" (dict "root" $ "name" $gatewayName "processedByOperator" true) | nindent 4 }}
spec:
  gatewayClassName: istio
  infrastructure:
    parametersRef:
      group: ""
      kind: ConfigMap
      name: {{ printf "%s-pod-options" .Values.ISTIO_EGRESS_GATEWAY_NAME }}
  listeners:
  - name: http
    port: 8080
    protocol: HTTP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-pod-options" .Values.ISTIO_EGRESS_GATEWAY_NAME }}
data:
  deployment: |
    spec:
      replicas: {{ default 1 .Values.REPLICAS}}
      template:
        spec:
          containers:
          - name: istio-proxy
            resources:
              requests:
                cpu: {{ .Values.CPU_REQUEST | quote }}
                memory: {{ .Values.EGRESS_GW_MEMORY_LIMIT | quote }}
              limits:
                cpu: {{ .Values.EGRESS_GW_CPU_LIMIT | quote }}
                memory: {{ .Values.EGRESS_GW_MEMORY_LIMIT | quote }}
          topologySpreadConstraints:
{{- if .Values.CLOUD_TOPOLOGIES }}
{{- range $v := .Values.CLOUD_TOPOLOGIES }}
          - topologyKey: {{ $v.topologyKey }}
            maxSkew: {{ $v.maxSkew | default 1 }}
            whenUnsatisfiable: {{ $v.whenUnsatisfiable | default "ScheduleAnyway" }}
            labelSelector:
              matchLabels:
                name: {{ printf "ns-%s" .Values.ISTIO_EGRESS_GATEWAY_NAME }}
{{- end }}
{{- else }}
          - maxSkew: 1
            topologyKey: '{{ .Values.CLOUD_TOPOLOGY_KEY }}'
            whenUnsatisfiable: ScheduleAnyway
            labelSelector:
              matchLabels:
                gateway.networking.k8s.io/gateway-name: {{ printf "ns-%s" .Values.ISTIO_EGRESS_GATEWAY_NAME }}
{{- end }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ printf "%s-route" .Values.ISTIO_EGRESS_GATEWAY_NAME }}
  annotations:
    helm.sh/hook: "pre-install, pre-upgrade"
    helm.sh/hook-weight: "-60"
    helm.sh/hook-delete-policy: "before-hook-creation"
    helm.sh/readiness-success: |
      {.status.parents[*].conditions[?(@.type=="Accepted")].status} != "False" &&
      {.status.parents[*].conditions[?(@.type=="ResolvedRefs")].status} != "False"    
    helm.sh/readiness-failure: |
      {.status.parents[*].conditions[?(@.type=="Accepted")].status} == "False" ||
      {.status.parents[*].conditions[?(@.type=="ResolvedRefs")].status} == "False"
  labels:
    {{- $routeName := printf "%s-route" .Values.EGRESS_GATEWAY_SERVICE_NAME | trunc 63 -}}
    {{- include "myapp.labels" (dict "root" $ "name" $routeName "processedByOperator" true) | nindent 4 }}
spec:
  parentRefs:
  - name: {{ printf "ns-%s" .Values.ISTIO_EGRESS_GATEWAY_NAME }}
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: '{{ .Values.EGRESS_FB_SERVICE_NAME }}'
      port: 8080
{{- end }}
{{- end }}