{{- if eq .Values.SERVICE_MESH_TYPE "Istio" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-pod-options" .Values.ISTIO_PUBLIC_GATEWAY_NAME }}
  labels:
    {{- $configMapName := printf "%s-pod-options" .Values.ISTIO_PUBLIC_GATEWAY_NAME | trunc 63 -}}
    {{- include "mesh.labels" (dict "root" . "name" $configMapName ) | nindent 4 }}
data:
  deployment: |
    spec:
      replicas: {{ default 1 .Values.REPLICAS}}
      template:
        spec:
          containers:
          - name: istio-proxy
            resources:
              requests:
                cpu: {{ .Values.CPU_REQUEST | quote }}
                memory: {{ .Values.PUBLIC_GW_MEMORY_LIMIT | quote }}
              limits:
                cpu: {{ .Values.PUBLIC_GW_CPU_LIMIT | quote }}
                memory: {{ .Values.PUBLIC_GW_MEMORY_LIMIT | quote }}
          topologySpreadConstraints:
{{- if .Values.CLOUD_TOPOLOGIES }}
{{- range $v := .Values.CLOUD_TOPOLOGIES }}
          - topologyKey: {{ $v.topologyKey }}
            maxSkew: {{ $v.maxSkew | default 1 }}
            whenUnsatisfiable: {{ $v.whenUnsatisfiable | default "ScheduleAnyway" }}
            labelSelector:
              matchLabels:
                name: '{{ .Values.ISTIO_PUBLIC_GATEWAY_NAME }}'
{{- end }}
{{- else }}
          - maxSkew: 1
            topologyKey: '{{ .Values.CLOUD_TOPOLOGY_KEY }}'
            whenUnsatisfiable: ScheduleAnyway
            labelSelector:
              matchLabels:
                gateway.networking.k8s.io/gateway-name: '{{ .Values.ISTIO_PUBLIC_GATEWAY_NAME }}'
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-pod-options" .Values.ISTIO_PRIVATE_GATEWAY_NAME }}
  labels:
    {{- $configMapName := printf "%s-pod-options" .Values.ISTIO_PRIVATE_GATEWAY_NAME | trunc 63 -}}
    {{- include "mesh.labels" (dict "root" . "name" $configMapName ) | nindent 4 }}
data:
  deployment: |
    spec:
      replicas: {{ default 1 .Values.REPLICAS}}
      template:
        spec:
          containers:
          - name: istio-proxy
            resources:
              requests:
                cpu: {{ .Values.CPU_REQUEST | quote }}
                memory: {{ .Values.PRIVATE_GW_MEMORY_LIMIT | quote }}
              limits:
                cpu: {{ .Values.PRIVATE_GW_CPU_LIMIT | quote }}
                memory: {{ .Values.PRIVATE_GW_MEMORY_LIMIT | quote }}
          topologySpreadConstraints:
{{- if .Values.CLOUD_TOPOLOGIES }}
{{- range $v := .Values.CLOUD_TOPOLOGIES }}
          - topologyKey: {{ $v.topologyKey }}
            maxSkew: {{ $v.maxSkew | default 1 }}
            whenUnsatisfiable: {{ $v.whenUnsatisfiable | default "ScheduleAnyway" }}
            labelSelector:
              matchLabels:
                name: '{{ .Values.ISTIO_PRIVATE_GATEWAY_NAME }}'
{{- end }}
{{- else }}
          - maxSkew: 1
            topologyKey: '{{ .Values.CLOUD_TOPOLOGY_KEY }}'
            whenUnsatisfiable: ScheduleAnyway
            labelSelector:
              matchLabels:
                gateway.networking.k8s.io/gateway-name: '{{ .Values.ISTIO_PRIVATE_GATEWAY_NAME }}'
{{- end }}
{{- end }}