{{- if eq .Values.SERVICE_MESH_TYPE "Istio" }}
{{- if not .Values.SKIP_EGRESS_GATEWAY_CREATION }}
---
kind: Service
apiVersion: v1
metadata:
  name: '{{ .Values.EGRESS_FB_SERVICE_NAME }}'
  annotations:
    helm.sh/hook: "pre-install, pre-upgrade"
    helm.sh/hook-weight: "-80"
    helm.sh/hook-delete-policy: "before-hook-creation"
  labels:
    {{- include "mesh.labels.service" (dict "root" . "name" .Values.EGRESS_FB_SERVICE_NAME ) | nindent 4 }}
spec:
  ports:
    - name: web
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    name: '{{ .Values.EGRESS_GATEWAY_SERVICE }}'
  clusterIP: None
  clusterIPs:
    - None
  type: ClusterIP
  sessionAffinity: None
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  internalTrafficPolicy: Cluster 
---
{{- $gwName := .Values.ISTIO_EGRESS_GATEWAY_NAME -}}
kind: Service
apiVersion: v1
metadata:
  name: '{{ .Values.EGRESS_GATEWAY_SERVICE_NAME }}'
  annotations:
    helm.sh/hook: "post-install, post-upgrade"
    helm.sh/hook-weight: "110"
    helm.sh/hook-delete-policy: "before-hook-creation"
  labels:
    {{- include "mesh.labels.service" (dict "root" . "name" .Values.EGRESS_GATEWAY_SERVICE_NAME ) | nindent 4 }}
spec:
  ports:
    - name: web
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    gateway.networking.k8s.io/gateway-name: {{ $gwName | quote }}
  clusterIP: None
  clusterIPs:
    - None
  type: ClusterIP
  sessionAffinity: None
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  internalTrafficPolicy: Cluster 
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ $gwName }}
  annotations:
    helm.sh/hook: "pre-install, pre-upgrade"
    helm.sh/hook-weight: "-100"
    helm.sh/hook-delete-policy: "before-hook-creation"
  labels:
    {{- include "mesh.labels" (dict "root" . "name" .Values.EGRESS_GATEWAY_SERVICE_NAME  "processedByOperator" true) | nindent 4 }}
spec:
  gatewayClassName: istio
  infrastructure:
    parametersRef:
      group: ""
      kind: ConfigMap
      name: {{ printf "%s-pod-options" $gwName }}
  listeners:
    - name: http
      port: 8080
      protocol: HTTP
---
{{- include "mesh.gateway.deploymentCustomizationMap" (dict
  "name" $gwName
  "values" (dict
    "root" .
    "replicas" .Values.REPLICAS
    "cpuRequest" .Values.CPU_REQUEST
    "cpuLimit" .Values.EGRESS_GW_CPU_LIMIT
    "memoryLimit" .Values.EGRESS_GW_MEMORY_LIMIT
    "topologies" .Values.CLOUD_TOPOLOGIES
    "topologyKey" .Values.CLOUD_TOPOLOGY_KEY
  )
) }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ printf "%s-route" $gwName }}
  annotations:
    helm.sh/hook: "pre-install, pre-upgrade"
    helm.sh/hook-weight: "-60"
    helm.sh/hook-delete-policy: "before-hook-creation"
  labels:
    {{- $routeName := printf "%s-route" $gwName | trunc 63 -}}
    {{- include "mesh.labels" (dict "root" . "name" $routeName "processedByOperator" true) | nindent 4 }}
spec:
  parentRefs:
    - name: {{ $gwName }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: '{{ .Values.EGRESS_FB_SERVICE_NAME }}'
          port: 8080
{{- end }}
{{- end }}