{{- if eq .Values.SERVICE_MESH_TYPE "Istio" }}
{{ $waypointName := .Values.WAYPOINT_NAME | default "waypoint" }}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ $waypointName }}
  labels:
    {{- include "mesh.labels" (dict "root" . "name" $waypointName "processedByOperator" true) | nindent 4 }}
    istio.io/waypoint-for: service
spec:
  gatewayClassName: istio-waypoint
  infrastructure:
    parametersRef:
      group: ""
      kind: ConfigMap
      name: {{ printf "%s-pod-options" $waypointName }}
  listeners:
    - name: mesh
      port: 15008
      protocol: HBONE
---
{{ include "mesh.gateway.deploymentCustomizationMap" (dict
  "name" $waypointName
  "values" (dict
    "root" .
    "replicas" .Values.REPLICAS
    "cpuRequest" .Values.WAYPOINT_CPU_REQUEST
    "cpuLimit" .Values.WAYPOINT_CPU_LIMIT
    "memoryLimit" .Values.WAYPOINT_MEMORY_LIMIT
    "topologies" .Values.CLOUD_TOPOLOGIES
    "topologyKey" .Values.CLOUD_TOPOLOGY_KEY
  )
) }}
{{- end }}