{{- if eq .Values.deploy_feature_flags.core.serviceMeshType "ISTIO" }}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: '{{ .Values.WAYPOINT_NAME }}'
  labels:
    {{- include "mesh.labels" (dict "root" . "name" .Values.WAYPOINT_NAME "processedByOperator" true) | nindent 4 }}
    istio.io/waypoint-for: service
spec:
  gatewayClassName: istio-waypoint
  listeners:
    - name: mesh
      port: 15008
      protocol: HBONE
{{- end }}